### ISSUE TITLE
Report scores of individual matches in search-for-xlinks

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#280]
For each cross-link PSM, in addition to the XCorr score, report the XCorrs of the two peptides individually.

Reported by: wsnoble

**Comment by wsnoble** [comment]
Sean, can you explain a bit how these auxiliary scores are computed?  I'd like to understand this better. In particular, why are the values inaccurate depending on the resolution of the precursor window?

**Comment by sjoemac** [comment]
I believe we had this discussion before.  In the top-n approach, each
peptide score is calculated using the remainder of the precursor mass as
the mass shift on the link site.  The crosslink peptide score is then
calculated using the sum of the two peptide scores.  This is the way Kojak
does its calculation. However, the true mass shift assigned to each peptide
within a crosslinked pair can be off from the each individual peptide's
calculated mass shift.  This mass shift affects the way the ions masses are
calculated around the crosslink sites and will affect the final XCORR
score.

The smaller the precursor tolerance window, the closer the "full, slower"
XCORR value calculated directly from the crosslinked peptides and the
"fast,inaccurate" XCORR value calculated by summing the individual peptide
scores using the remainder precursor mass shift will be because the pairs
of peptides chosen will have a "precursor remainder" mass shift closer to
the true mass shift calculated directly from the crosslinked peptide.

Currently, sfx uses the "fast,inaccurate" method when using top-n and the
"full, slower" method when doing the full quadratic search.

Thanks,
Sean
