### ISSUE TITLE
Automatically track mapping of parameters to commands

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#336]
We need a data structure that keeps track of the matrix of (options x commands). It would be convenient if the code could produce this matrix automatically as part of the documentation.  And the (currently manually edited) statements about which commands a given option is available for could also be automatically generated.

One question is whether it makes more sense to define the option-to-command mapping in Params.cpp when the option is defined (e.g., have a required argument to the Init{Bool,...} options that is a list of commands) or when the command is defined (i.e., as is currently done by getOptions).  I guess it's probably more intuitive for the coder to do it the way it's currently set up.

Kaipo, is there an enumerate type of command that we could use to iterate over all commands? And is there an easy way to iterate over all options?

Bill

---

I think it might make more sense to define the mapping in Params.cpp, just so everything is in one place. It wouldn't be hard to change but probably time consuming since we have to go through every single parameter and change it. Some of the parameters that are ubiquitous like overwrite and verbosity we would need to remember to add to when we add a new command.
It would be pretty easy to iterate over both commands and options if we need to.

---

Reported by: wsnoble

**Comment by wsnoble** [comment]
This is still a problem.  Here is a user report:

"I don’t know if you are aware of this but tide-index was happy to take on the “—isotope-error” parameter even though it’s presumably not doing anything because that should go into tide-search."

**Comment by kfattila** [comment]
I got a student to do this task as a summer practice project. Let's discuss this task in detail during the next lab meeting. A

**Comment by hlocon1309** [comment]
For a simple solution, I have considered some facts that I found in code.
1. Each app has their own list of parameters already defined.
2. After parsing input parameters, it is possible to compare the parsed params against default params of the current app.
3. If there exists one parameter that doesn't match, crux halts with an error message.
4. For the previous step, only the first parameter found raises the error, if there are more, they will not be checked until the next run.

**Comment by wsnoble** [comment]
"Each app has their own list of options already defined."

Yes, but we should double check these, because I am not sure they are currently accurate.

"After parsing input parameters, it is possible to compare the parsed options against default options of the current app."

Yes, this is the step that I guess you have implemented.

"For the previous step, only the first option found raises the error, if there are more, they will not be checked until the next run."

This is not ideal.  It would be better to traverse the full list, and set a Boolean ("error_found") if an error is found and reported. Then exit with an error at the end of the loop.

**Comment by kfattila** [comment]
This has been solved by Ruffino.
