### ISSUE TITLE
Percolator does not report all of the PSMs

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#356]
It appears that Crux Percolator does not report as many PSMs as the corresponding stand-alone version. I ran three files through Crux Percolator, and then I used the resulting make-pin.pin file as input to the stand-alone version. Both report the same number of input PSMs (129,212), but the Crux version only yields a total of 26,342 PSMs, whereas the stand-alone version yields 129,212 PSMs.

The various files can be found here:

http://noble.gs.washington.edu/~wnoble/proj/malaria/2016histone-msms/results/bill/2016-09-03percolator-bug/

Reported by: wsnoble

**Comment by wsnoble** [comment]
OK, here is the solution to this problem, as outlined in an email I wrote on 9/22:

"As I understand it, the "only-psms" flag implicitly turns on target-decoy competition in order to maintain backward compatibility with MatrixScience. I'd like to fix this problem in Crux Percolator, since we don't have to worry about MatrixScience compatibility.  As I understand it, we can avoid this problem by always explicitly indicating whether to do TDC.  This means we should have a "--tdc T|F" option in Crux.  If we get "--tdc F", then we call Percolator with "--post-processing-qvality," and if we get "--tdc T", then we call Percolator with "--post-processing-tdc". The default behavior for Crux Percolator could be to perform TDC only if the targets and decoys are provided in separate files, and no TDC if they are provided in a single file. Kaipo, is the latter easy to implement?"

Kaipo, would you please make this change?

Bill

**Comment by kaipot** [comment]
Here is a patch, it doesn't change behavior based on whether targets/decoys are provided in separate files though. I think it is hard to determine a user's intent, unless the parameter is changed from its default value explicitly.

[tdc.zip](https://github.com/crux-toolkit/crux-toolkit/files/559444/tdc.zip)
