### ISSUE TITLE
Seg fault from tide-index with many mods

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#384]
I tried to do a search with many mods, and I got a core dump.  Here is the command line:

crux tide-index --mods-spec 1A+3.010065,1A+4.007099,1F+10.027228,1G+3.003745,1I+7.017164,1K+8.014199,1K+6.020129,1K+1.99407,1K+42.010565,1K+226.077598,1K+27.994915,1K+70.041865,1K+114.042927,1K+86.036779,1K+114.031694,1K+68.026215,1K+86.000394,1K+59.045045,1K+28.0313,1K+42.04695,1K+56.026215,1K+100.016044,1L+7.017164,1M+15.994915,1R+10.008269,1R+6.020129,1R+0.984016,1R+14.01565,1R+28.0313,1S+79.966331,1T+5.010454,1T+79.966331,1V+6.013809,1Y+10.027228,1Y+79.966331,1K+45.029395 --overwrite T --output-dir foo sample.fasta foo

The fasta file is attached.

[sample.txt](https://github.com/crux-toolkit/crux-toolkit/files/958382/sample.txt)

**Comment by wsnoble** [comment]
I verified that this problem still exists, after Kaipo's fix for Issue #390. I suspect the problem is similar to that one, in that it's due to using legacy modification code. Kaipo, can you check on this?

**Comment by kaipot** [comment]
This was the issue of the stack overflowing when generating modified peptides, due to too many combinations. I'd created a fix for it but in testing you mentioned that it was twice as slow as the old code.

I never managed to get the performance improvements that I was hoping for, and I'm not sure it can be optimized meaningfully without causing other problems (reintroducing the issue of creating too many temp files, or using memory in a way that is not scalable).

Ideally we would be able to use the original code, if it fails then switch to the fixed slower version. However I don't think there is really a way to recover from a stack overflow. Having a parameter to control which code is used also doesn't seem like a good solution, from a user's perspective. But I can't think of a better idea.

**Comment by wsnoble** [comment]
Can you re-send the patch? A factor of 2 is not too bad, especially since that was in the worst case (using tons of mods). I think we'll probably just go with your new version, but I can do some testing.

**Comment by kaipot** [comment]
[tide-mods.txt](https://github.com/crux-toolkit/crux-toolkit/files/1099589/tide-mods.txt)

Hi Bill, here is the patch.

**Comment by wsnoble** [comment]
OK, I have checked this patch, and it looks good.  Please be sure to add an update to the release notes, along the lines of

"Improved handling of modifications in tide-index, allowing for indices containing many different types of modifications."

**Comment by wsnoble** [comment]
Wait, I thought my smoke tests pass, but they didn't. I seem to be getting different results in 

test/smoke-tests/good_results/tide-mods1min.txt

Can you take a look at this to see if you can track down the source of the difference?

**Comment by kaipot** [comment]
Whoops, there was a bug. It was always writing the unmodified peptide, even if min-mods was > 0. Good thing that test is there, here is an updated patch with fix:
[tide-mods2.txt](https://github.com/crux-toolkit/crux-toolkit/files/1103116/tide-mods2.txt)

**Comment by wsnoble** [comment]
OK, Fangfei and Christian report that this seems to be working properly. I think it's safe to check it in now.
