### ISSUE TITLE
MacOS installation problems with JDK

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#431]
I recently installed JDK and my build started failing with this error:

bash-3.2$ make
[  1%] Generating crux_version_header, crux_version.h
[  1%] Built target crux_version
[  4%] Built target protobuf-3.0.0
[  7%] Built target gflags-2.2.1
[  7%] Performing install step for 'ProteoWizard'
CREATING GENERICALLY NAMED SYMBOLIC LINKS TO LIBRARIES
arg:--prefix=/Users/wnoble/proj/crux-toolkit/ext
parsing --prefix=/Users/wnoble/proj/crux-toolkit/ext
path:/Users/wnoble/proj/crux-toolkit/ext
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file

Regarding this issue, Sean reported the following:

I had to create a symbolic link to the jni_md.h to where proteowizard was trying to find it in my jdk install.
i.e.

static-209-70:issue_427 mcilwain$ cd /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/include/
static-209-70:include mcilwain$ ls
classfile_constants.h	jawt.h			jni.h			jvmticmlr.h
darwin			jdwpTransport.h		jvmti.h

sudo ln -s ./darwin/jni_md.h

I tried this on my mac, but it had no effect on the error message. Any ideas?

**Comment by CharlesEGrant** [comment]
I think Sean's issue is actually unrelated to the issue Bill saw. I think the issue Sean saw is related to some Java interface code in Proteowizard that breaks the Proteowizard build if it can't find the header file in the local Java installation.  The issue Bill is seeing is related to ext/create_link.sh which is called after building Proteowizard to make links to the BOOST libraries built by Proteowizard. Proteowizard "decorates" the names of the BOOST libraries with the compiler and BOOST version numbers. This is super inconvenient, so we create links with "undecorated" names. This works on the TeamCity build and on my machine. Those are both out-of-source builds, and I suspect Bill was using and in source build.

**Comment by CharlesEGrant** [comment]
I can't reproduce this problem with the current code with an in-source or out-of-source build. Bill, are you still seeing this error? What happens if you cd into ext and run create_link.sh?

**Comment by wsnoble** [comment]
I cd into ext and run create_link.sh and get the error shown above. I am using /bin/ln. Here is a specific command that is problematic. 

$ cd ext/lib
$ ln -s -f libboost_date_time-mt-s.a libboost_date_time-xgcc42-mt.a libboost_date_time.a
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
$ ls -al libboost_date_time.a 
lrwxr-xr-x  1 wnoble  staff  30 Oct 25 10:18 libboost_date_time.a@ -> libboost_date_time-xgcc42-mt.a


I am running MacOS version 10.14.3 (18D109).

**Comment by CharlesEGrant** [comment]
$ ln -s -f libboost_date_time-mt-s.a libboost_date_time-xgcc42-mt.a libboost_date_time.a

So in that command three files are named, which isn't valid for 'ln'. What happens if you run just

ln -s -f  libboost_date_time-xgcc42-mt.a libboost_date_time.a

Could you also try running 

which -a ln

to see if you have multiple copies of 'ln' installed?

Finally could you trying running

bash -x create_links.sh

That should let us see exactly where the error is occurring.

**Comment by CharlesEGrant** [comment]
You explanation that the 'ln' command line with three files named was exactly the command that was being executed by the shell script clarified everything! 

This bug would only show up if you'd done multiple in-source builds which resulted in two or more versions of libraries with the same name, but different 'decorations' being in the directory. I think 'libboost_date_time-mt-s.a' is left over from a previous build of PWIZ with BOOST 1.57. Try running 'make deep-clean' from the root directory of the repository, and veryifying that ext/lib no longer contains any lib files. Then try rebuilding.

To permanently fix this problem will have to make the create_links.sh script much more robust, so that it spots problems like this.

**Comment by wsnoble** [comment]
That did indeed eliminate the problem. But I now get a pwiz build problem (see attached log). This is on Mohave 10.4.3.

bash-3.2$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
[log.txt](https://github.com/crux-toolkit/crux-toolkit/files/3087463/log.txt)

**Comment by CharlesEGrant** [comment]
The error is the log file is

/Users/wnoble/proj/crux-toolkit/ext/build/src/ProteoWizard/libraries/boost_1_67_0/boost/atomic/detail/ops_gcc_x86_dcas.hpp:408:16: error: address argument to atomic builtin cannot be const-qualified ('const volatile boost::atomics::detail::gcc_dcas_x86_64::storage_type *' (aka 'const volatile unsigned __int128 *') invalid)
        return __sync_val_compare_and_swap(&storage, value, value);

This is the error I mentioned in email to the crux-internal group last week. BOOST 1.69 actually violates the C++ spec, but none of the compilers cared about until the most recent version of Apple's build of clang. Your version of clang is

Apple LLVM version 10.0.1 (clang-1001.0.46.3)

the last version of clang that works is

Apple LLVM version 10.0.0 (clang-1000.11.45.5)

This is fixed in later versions of BOOST, but that won't do us any good until PWIZ updates to the new version of BOOST.

I was able to work around this through the following steps:

1. Delete the XCode application
2. Reboot
3. Download and install XCode 10.1 from the Apple Developer's web site. THis requires an Apple Developer account, I can hook you up with a copy if you don't have an account

Until PWIZ updates to a newer version of BOOST we'll have to stick at XCode 10.1.

**Comment by wsnoble** [comment]
OK, thanks. Please update the installation guide to reflect this, and notify the pwiz team if you haven't already.
