### ISSUE TITLE
How to merge  multiple fractions into one file when executing tide-search?

### ISSUE THREAD

**Issue by lhuangjs** [crux-toolkit/crux-toolkit#455]
I have raw data with 8 fractions, I want to store them as a binarized fragmentation spectra when executing `tide-search`. So I use the parameter `--store-spectra`. But it cannot work and warn:

```
FATAL: Cannot use store-spectra option with multiple input spectrum files
```
- command
```
crux tide-search --parameter-file tide.properties \
--store-spectra \
fractionated1.raw \
fractionated2.raw \
fractionated3.raw \
fractionated4.raw \
fractionated5.raw \
fractionated6.raw \
fractionated7.raw \
fractionated8.raw \
library
```
So, how can I do if I want to achieve my aim? 
Thanks!

**Comment by wsnoble** [comment]
Sorry, but as the error message indicates, we don't have this functionality
implemented right now. The closest you could get would be to (1) run
tide-search separately on each file and then merge the search results or
(2) run tide-search separately on each file with the --store-spectra option
and then run tide-search again on the resulting spectrumrecords files.

We are working on functionality that will make it so that you can just
convert the spectra prior to calling tide-search:

https://github.com/crux-toolkit/crux-toolkit/issues/439

Bill
