### ISSUE TITLE
Possible bug in protein assignment (Comet bug?)

### ISSUE THREAD

**Issue by mriffle** [crux-toolkit/crux-toolkit#472]
I hope I'm not missing something silly here. I'm seeing these two results for the same peptide for two different scans:

```
<search_hit hit_rank="1" peptide="DLFGR" peptide_prev_aa="K" peptide_next_aa="F" protein="decoy_C36B1.12a" num_tot_proteins="3" num_matched_ions="1" tot_num_ions="8" calc_neutral_pep_mass="606.312561" massdiff="0.785876" num_tol_term...
    <alternative_protein protein="decoy_C36B1.12b"/>
    <alternative_protein protein="decoy_C36B1.12c"/>
    <search_score name="xcorr" value="0.247"/>
    <search_score name="deltacn" value="0.000"/>
    <search_score name="deltacnstar" value="0.000"/>
    <search_score name="spscore" value="0.5"/>
    <search_score name="sprank" value="15"/>
    <search_score name="expect" value="9.99E+02"/>
   </search_hit>
```

```
<search_hit hit_rank="3" peptide="DLFGR" peptide_prev_aa="K" peptide_next_aa="F" protein="sp|P0A6M2|DSBB_ECOLI" num_tot_proteins="5" num_matched_ions="6" tot_num_ions="8" calc_neutral_pep_mass="606.312561" massdiff="-1.044263" num_to...
    <alternative_protein protein="decoy_C36B1.12a"/>
    <alternative_protein protein="decoy_C36B1.12b"/>
    <alternative_protein protein="decoy_C36B1.12c"/>
    <alternative_protein protein="decoy_T05C3.2"/>
    <search_score name="xcorr" value="0.800"/>
    <search_score name="deltacn" value="0.014"/>
    <search_score name="deltacnstar" value="0.000"/>
    <search_score name="spscore" value="266.9"/>
    <search_score name="sprank" value="1"/>
    <search_score name="expect" value="1.87E+01"/>
   </search_hit>
```

The way I read this, the same peptide (with the same flanking amino acids) has two different lists of matched proteins. In one case it's a decoy hit, in one case it's not. I don't understand how this is possible. This is causing my code some problems since I assumed the same protein list would be reported for the same peptide. I'm removing that assumption from my program, but thought I'd report this since I'm confused by it.

**Comment by wsnoble** [comment]
This certainly seems like a problem. Which crux command generated this
output? Did you also produce a .txt file, and is the problem in there as
well?

**Comment by mriffle** [comment]
I send you the path to the data in email.

**Comment by wsnoble** [comment]
I looked at the comet.target.txt file produced by Comet, and the problem seems to be there:

bash-4.2$ awk -F "\t" '$14 == "DLFGR"' comet.target.txt 
17674   1       608.105713      607.098436      606.312561      0.0000  0.5390  15      0.2474  4       1       8       17566   DLFGR   K.DLFGR.F       	decoy_C36B1.12a,decoy_C36B1.12b,decoy_C36B1.12c KF      9.99E+02
59688   1       606.275574      605.268297      606.312561      0.1496  266.8553        1       0.8002  4       6       8       25560   DLFGR   K.DLFGR.F               sp|P0A6M2|DSBB_ECOLI,decoy_sp|P0A6M2|DSBB_ECOLI,decoy_C36B1.12b,decoy_C36B1.12c,decoy_T05C3.2   KF      1.87E+01
63390   1       606.340393      605.333117      606.312561      0.0715  125.6802        19      0.9966  5       5       8       24800   DLFGR   K.DLFGR.F               sp|P0A6M2|DSBB_ECOLI,decoy_sp|P0A6M2|DSBB_ECOLI,decoy_C36B1.12b,decoy_C36B1.12c,decoy_T05C3.2   KF      5.33E+01

Here is the Crux command line:

COMMAND LINE: C:\crux-3.2.46bb0c1\crux-3.2\bin\crux.exe comet 28Oct2019-Velos-DDA-ingel-JR07.mzML --output-dir crux-output-JR07 --decoy_search 1 --output_percolatorfile 1 elegans_PRJNA1376_WBPS14_ecoli_UP000000625_contam.fasta
