### ISSUE TITLE
Do not report peptides with 0 quantification

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#479]
From esvecha@gmail.com on the crux-users list:

> "Firstly, the quantification will fail if there are decoy PSMs listed under your FDR of choice in the .percolator.target.psms file. Every returned quantity will be zero because the decoy_sp|XXXX will not be in the fasta file database. This might not be the case with a tide search, I'm not sure if the generated database there would be more useable. I, however, was using this through a comet search. So my original database file doesn't have the decoys. Not that they need to be quantified anyway, perhaps ignoring them when running spectral counts would be an ideal implementation?"

Seems like a reasonable suggestion.  It might be as simple as just refusing to print any protein (or peptide) if its quantification is zero.  Could be done by modifying writeRanked{Proteins,Peptides} in src/io/OutputFiles.cpp.

**Comment by bmx8177** [comment]
I was looking at this and got confused why there were decoys in the target file. Upon looking at the crux-users thread it appears that you figured out what the issue was (comet+percolator weirdness). However, it was unclear from the thread whether you had fixed everything you wanted fixed. Can you comment on this @wsnoble? Are we able to close this issue?

**Comment by wsnoble** [comment]
The modification I proposed originally (do not report peptides with 0 quants) doesn't make sense.  I could imagine adding a check for decoys in the given file and complaining if they are there. But that would require that we know the syntax for specifying targets vs. decoys.  So I think it's simplest just to close this one.
