### ISSUE TITLE
Theoretical spectrum is independent of precursor charge in calculating XCorr

### ISSUE THREAD

**Issue by younglululu** [crux-toolkit/crux-toolkit#493]
When reading the Tide-search code, I noticed that in constructing theoretical spectrum, +1/+2 b/y ions are always created regardless of the charge state of precursor, which is inconsistently with the claim in the Tide paper "For spectra with precursor charge of 3 or higher, doubly charged ions are included in the theoretical spectrum."

Here is some details to track the problem:

In app/tide/active_peptide_queue.cc:
```
void ActivePeptideQueue::ComputeTheoreticalPeaksBack() {
  theoretical_peak_set_.Clear();
  Peptide* peptide = queue_.back();
  peptide->ComputeTheoreticalPeaks(&theoretical_peak_set_, current_pb_peptide_,
                                   compiler_prog1_, compiler_prog2_);
}
```

And in app/tide/peptide.cc:
```
template<class W>
void Peptide::AddIons(W* workspace) const {
  // Use workspace to assemble all B and Y ions. workspace will determine
  // which, if any, associated ions will be represented.
  double max_possible_peak = numeric_limits<double>::infinity();
  if (MaxBin::Global().MaxBinEnd() > 0)
    max_possible_peak = MaxBin::Global().CacheBinEnd();

  vector<double> aa_masses = getAAMasses();

  // Add all charge 1 B ions.
  double total = aa_masses[0];
  for (int i = 1; i < Len() && total <= max_possible_peak; ++i) {
    workspace->AddBIon(total, 1);
    total += aa_masses[i];
  }

  // Add all charge 1 Y ions.
  total = aa_masses[Len() - 1];
  for (int i = Len()-2; i >= 0 && total <= max_possible_peak; --i) {
    workspace->AddYIon(total, 1);
    total += aa_masses[i];
  }

  // Add all charge 2 B ions.
  max_possible_peak = max_possible_peak*2 + 2;  //adjust for larger charge
  total = aa_masses[0];
  for (int i = 1; i < Len() && total <= max_possible_peak; ++i) {
    workspace->AddBIon(total, 2);
    total += aa_masses[i];
  }

  // Add all charge 2 Y ions.
  total = aa_masses[Len() - 1];
  for (int i = Len()-2; i >= 0 && total <= max_possible_peak; --i) {
    workspace->AddYIon(total, 2);
    total += aa_masses[i];
  }
}
```

**Comment by kfattila** [comment]
The singly and double-charged theoretical peaks are generated for all peptides at the beginning because at this point we do not know the charge state of the observed spectrum. Whether to consider singly or doubly charged peaks in scoring, it depends on the charge state of the observed spectra. 

The peptide contains its theoretical peaks in a ST_TheoreticalPeakSet class.
This class has two arrays for the theoretical peaks in file theoretical_peak_set.c :  
   TheoreticalPeakArr peaks_[2];    //in line 526
    peaks_[0].Init(capacity);        // in lines: 447-448
    peaks_[1].Init(capacity);

peaks_[0] contains the singly charge theoretical peaks, 
peaks_[1] contains the doubly charged theoretical peaks. 

Now, there is a member function GetPeaks: in line 506
This will copy: 
1. the singly charged theoretical peaks peaks_[0] to peaks_charge_1
AND it will copy
2a: the singly charged theoretical peaks peaks_[0] to peaks_charge_2  AND
2b: the doubly charged theoretical peaks peaks_[1] to peaks_charge_2

These are in lines: 514-516

Once the peptide is loaded in the ActivePeptideQueue::SetActiveRange, then it gerenrates two "programs" by:
ComputeTheoreticalPeaksBack().

More specifically: in peptide.cc:200, it compiles compiler_prog1 and compiler_prog2. 
The compiler_prog1 contains the singly charged theoretical peaks, and
the compiler_prog2 contains the singly and doubly-charged theoretical peaks. 

So, now in the scoring happens in TideSearchApplication.cpp, in the function TideSearchApplication::collectScoresCompiled(.., charge).
This calls the correct compiled progam depending on the charge state of the observed spectrum:
const void* prog = active_peptide_queue->NextPeptide()->Prog(charge);
See: peptide.h: 185

**Comment by younglululu** [comment]
Thanks, Attila! It makes sense to me!

**Comment by wsnoble** [comment]
Since this was so hard to figure out, I suggest that perhaps a version of Attila's explanation should perhaps be incorporated into the code as a block comment. What do you think?

**Comment by younglululu** [comment]
Yes, I think it's a good idea and I will do it.
