### ISSUE TITLE
fasta database not found in tide-search

### ISSUE THREAD

**Issue by infusini** [crux-toolkit/crux-toolkit#507]
Hi,

I'm running tide-search but I'm running into an issue where the process fails with an error:

```
INFO: Database not provided; will use empty database.
WARNING: empty protein id string in tab delimited file. searching database to find proteins to match peptide sequence
ERROR: Failed to open fasta file
FATAL: Failed to parse database, cannot create iterator
```

I use a script to run the search:

```
./man-search/narrow/tide-search-narrow.sh /data/small.mgf  /data/test.fasta
```

Fasta database, mgf file, script and tide-search logs can be found here: https://drive.google.com/drive/folders/10vyEMUlU4OoEnpWB-S3yRG_MaZuJABop?usp=sharing

 I have tried both `crux-4.0.Linux.x86_64` and `crux-4.0.6818dcc.Linux.x86_64`

I have also tried to run tide-index first but I still get the same error.

Please let me know if you can help.

Best,

Giuseppe

**Comment by infusini** [comment]
Hi, I  have investigated this a bit further and found that the issue is coming from a combination of parameters.

For example:
-  `--min-length 3` causes the issue, raising it to 4 (without any mods) solves the problem
-  the combination of mono and di-oxidation `--mods-spec C+57.02146,2MWYH+15.994915,2MWY+31.989829` causes the same problem. Removing either the `2MWYH+15.994915` or `2MWY+31.989829` solves the issue.

I hope this helps.

**Comment by wsnoble** [comment]
I was able to reproduce this problem. The issue, I believe, is related to the use of the --brief-output flag, which was introduced recently.  The tide-search output files gets re-parsed at the end of the search in order to produce the PIN output, and this parsing step is broken when the output is in brief format. For the end user, there is no easy fix to this other than removing the --brief-output option.

On our side, the fix is to add documentation and some error checking to ensure that --brief-output T is not used in conjunction with --pin-output or the other output format files.

**Comment by wsnoble** [comment]
I have checked in the fix described above.
