### ISSUE TITLE
Question about tide-percolator

### ISSUE THREAD

**Issue by nattzy94** [crux-toolkit/crux-toolkit#510]
Hi,

I am running tide+percolator on my mass spectra. My understanding is that Percolator re-estimates the FDR of PSMs identified by tide and should not change the peptide identifications. However, in my case, I see that after post-processing by Percolator, some spectra have different peptide matches.

For instance, tide-search matches the following spectrum to the peptide 'GGGGTSIR':

scan | charge | score | peptide | q-value
-- | -- | -- | -- | --
6958 | 2 | 0.00451085 | GGGGTSIR | 0.653717

However, after Percolator, the identified peptide is changed to 'VESEIK':

file_idx | scan | charge | spectrum precursor m/z | spectrum neutral mass | peptide mass | percolator score | percolator q-value | percolator PEP | distinct matches/spectrum | sequence | protein id | flanking aa
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 6958 | 2 | 352.6949 | 703.3752 | 703.3752 | -0.3856121 | 0.19973661 | 0.67780709 | 3802 | VESEIK | ENST00000378024_(+1)_3,ENST00000525875_(+3) | KV

Am I wrong in saying that Percolator only re-estimates FDRs? Or does it also re-assign spectra to peptides after re-estimating FDR?

**Comment by wsnoble** [comment]
If you pass more than one PSM per spectrum into Percolator, then it will
sometimes re-rank the PSMs relative to that spectrum.  This is the
difference between the two Percolator series in Figure 1 of the original
Percolator paper:

[image: image.png]

https://www.nature.com/articles/nmeth1113/figures/1

Figure 2 shows a specific example of a PSM that was corrected by taking the
2nd-ranked match.

https://www.nature.com/articles/nmeth1113/figures/2

If you don't want this behavior, then you can set "--top-match 1" in your
initial search.

Bill

**Comment by nattzy94** [comment]
Thank you for the reply. 

I would also like to inspect the peptide-spectral matches to validate their quality. Is there a visualisation software that is compatible with the results of tide + percolator?

I would like to obtain something like this (using SearchGUI + PeptideShaker):

<img width="1166" alt="ENST00000442722_(+1)_8 QSRGYTISK deamidatedQ b-ions" src="https://user-images.githubusercontent.com/48880365/123920468-90b62c80-d9b8-11eb-8ddd-6a9cb35c08a6.png">

I know tide-Percolator is compatible with the trans-proteomic pipeline but I don't think the TPP can be used to visualise peptide-spectral matches?

**Comment by wsnoble** [comment]
PeptideShaker supports Tide output, but I don't think it supports
Percolator output, unfortunately. I am not aware of other ways to visualize
PSMs, but I've sent a few emails to ask others and will let you know if I
find anything.

Bill

**Comment by mriffle** [comment]
@nattzy94,

Bill contacted me letting you know about your need to view these results. Our team at the UW has written software called Limelight that will let you visualize proteomics results (proteins, peptides, psms, spectra, etc) from a large number of possible pipelines, including Tide + Percolator. You can learn more at https://limelight-ms.org/

But briefly: The way data gets into Limelight is to first convert the output of your pipeline to Limelight XML. We have written a number of converters for this, including a Tide + Percolator converter. However, it's been some time since I wrote that converter and it may not work as-is... but I would be very happy to work with you to get it up to snuff. This converter can be found at https://github.com/yeastrc/limelight-import-crux-tide-percolator

If you take a look at Limelight and think this is software you'd like to use, I'd be happy to provide any assistance you might need to get up and running.

Mike

**Comment by nattzy94** [comment]
Hi Mike, this is really helpful. I will try out limelight and get back to you if I have any issues.
