### ISSUE TITLE
Stochasticity of Tailor scores across different machines

### ISSUE THREAD

**Issue by younglululu** [crux-toolkit/crux-toolkit#516]
When I tried to search a toy .mzXML file to a toy fasta file (see below), by using the following options: --top-match 5
I found that 5 out of ~1800 resultant PSMs have slightly different Tailor scores when I ran crux in two different machine.
I expected the Tailor score to be deterministic, I am wondering what's the reason of such observed stochasticity? Thanks!

https://github.com/younglululu/crux-toolkit/blob/master/test/smoke-tests/diameter_test.mzXML
https://github.com/younglululu/crux-toolkit/blob/master/test/smoke-tests/small-yeast.fasta

**Comment by wsnoble** [comment]
Yang, can you please clarify precisely which two different machines led to different results and post the output files here?  You should also include the full command line that you used.
Thanks.
Bill

**Comment by younglululu** [comment]
1. The two different machines are my laptop (ubuntu 18.04) and the lab cluster (redhat).
2. The command I used is "crux diameter --overwrite T --top-match 5  --prec-ppm 10 --frag-ppm 10 diameter_test.mzXML small-yeast.fasta". Though diameter hasn't been released, it will internally call use tide-search with the settings "--precursor-window 10 --precursor-window-type mz --top-match 5 --use-tailor-calibration T --concat T" and enumerate charge state from 1 to 5. The easiest way to reproduce the result is to run the smoke test diameter.feature in my own branch of crux (https://github.com/younglululu/crux-toolkit).
3.  The partial results:

**Comment by kfattila** [comment]
Hi,

could you please run the same experiment on that two machines, but reporting all the psms, I.e.  —top-match 9999999 and send me a link to the results.  Thanks.

**Comment by kfattila** [comment]
Could you also run the smoke tests on your laptop and let me know if all passed. Thanks

**Comment by younglululu** [comment]
Hi Attila,

The experiments run on two machines with the option "—top-match 9999999" can be accessed below:
https://noble.gs.washington.edu/~ylu465/cluster.diameter-search.txt
https://noble.gs.washington.edu/~ylu465/laptop.diameter-search.txt

It's difficult to configure the smoke test environment on my laptop. So all my tests were ran on the cluster. So far it passed because I explicitly generated both the expected and actual file on the same machine.

**Comment by kfattila** [comment]
Could you please check if there are different xcorr scores in the two results files? 

My guess is that, the issue arises from double imprecision which is also governed by CPUs. If you could run the smoke tests on your laptop we could see if there is other rounding errors in other tests such as those related to exact p values.

**Comment by younglululu** [comment]
It's not the problem of rounding error, because I can confirm the xcorr scores are strictly the same

**Comment by kfattila** [comment]
Thanks a lot! Indeed, now the difference is too big, it does not look like a rounding error. However, the numbers in the text files are different from the numbers you posted above.

Could you also reproduce this error with tide-search? 
Could you please send me also the tide-INDEX logs and params from both computers?
Could you please also prepare some toy data for me so that I could reproduce the experiment? I can take a look at this on Monday morning.

Thanks, A.

**Comment by younglululu** [comment]
Yes, the error can be reproduced in tide-search

Here is the command I used (It is a toy DIA data with 20 m/z isolation window. I convert the .mzXML into .mgf file with manually assigned charge state +5): 
crux tide-search --overwrite T --top-match 9999999 --precursor-window 10 --precursor-window-type mz --use-tailor-calibration T --concat T diameter_test-charge-5.mgf small-yeast.fasta

where the .mgf and .fasta files can be accessed here:
https://noble.gs.washington.edu/~ylu465/diameter_test-charge-5.mgf
https://noble.gs.washington.edu/~ylu465/small-yeast.fasta

And the output in two separate machines can be accessed here:
https://noble.gs.washington.edu/~ylu465/cluster.tide-search-charge5.txt
https://noble.gs.washington.edu/~ylu465/local.tide-search-charge5.txt

**Comment by kfattila** [comment]
Could you please also share the tide INDEX logs and Params files from both machines (4 files in total)? Thanks

**Comment by younglululu** [comment]
The param files are as follows:
https://noble.gs.washington.edu/~ylu465/cluster.tide-search.params.txt
https://noble.gs.washington.edu/~ylu465/local.tide-search.params.txt

There is NO index logs because no tide-index is explicitly called.

**Comment by kfattila** [comment]
Thanks a lot! Could you please send me the tide-search log files from both machines and could you also rerun tide-search with the option —peptide-list T
this should generate a file with a list of peptides along with their masses. Could you please do these for both machines? Thanks!

**Comment by kfattila** [comment]
Hi, 

I looked at the problem. I re-run my crux and my results are identical to the ones from the cluster. First of all, I think the problem is not with Tailor, but the problem lies in the candidate peptide selection, the index file generation, and in the function "int ActivePeptideQueue::SetActiveRange ". The heaviest peptide in the index file is "DYAWYWGDFFFLEESELIFDGVFNISPHPMYSIGYLGYYGLSLICNDYK	5913.7041" let's call it peptide A, and there is one decoy with the same mass, let's call it peptide B. These peptides are the last ones in the queue. The heavies spectrum from the mass spec file is the one with SCAN ID 82 (and 41). This spectrum should be score against two peptides A and B. Strangely, this spectrum is scored against three peptides: twice with peptide A, and once peptide B. You can see this in your results as well in the cluster and on your local PC. there are two PSM lines with exactly the same information!
I rerun an old CRUX version, Crux version: 3.2-78825c96 compiled on May/17/2019. This was compiled before Tailor, and this problem already existed. I also run tide-search with exact-p-value T option. This uses a different function to manage the active peptide queue (int ActivePeptideQueue::SetActiveRangeBIons), and the problem still persists.  Therefore, this bug is not raised by Tailor. 

Now, back to the original question: why you get different Tailor scores on your local PC and on the cluster: I do not know. However, I noticed that you use different versions of CRUX on cluster and on local. generated by Crux version 4.0-35f99d7-2021-07-29 vs. generated by Crux version 4.0-3e32760f-2021-07-29. First, could you make sure that you use the same version? 

For the short term, you can overcome this bug by generating more and larger peptides, You can add missed cleavages or modifications. You can also try to fix this in "int ActivePeptideQueue::SetActiveRange".

Alternatively, if this is not very urgent to you, you can wait, and I will try to fix this by 1st of September.

**Comment by kfattila** [comment]
Hi,

I found the bug in Tailor. Tailor assumes to have at least four PSM scores, not necessarily from the active peptide range, in order to determine the Q100. In your experiment setting, the active peptide queue reaches the end of the peptides and it cannot have 4 PSM scores. It uses a Q100 from scores[3] which is a random slot in the RAM. I will send you a fix and I will open a new issue about the new bug I found tomorrow.

**Comment by kfattila** [comment]
Hi, 

In order to fix the bug could you change the following code in TideSearchApplication.cpp: line around 677

```
       //Implementation of the Tailor score calibration method, by AKF
        double quantile_score = 1.0;
        if (Params::GetBool("use-tailor-calibration")){
          vector<double> scores;
          double quantile_th = TAILOR_QUANTILE_TH;
          // Collect the scores for the score tail distribution
          for (TideMatchSet::Arr2::iterator it = match_arr2.begin();
            it != match_arr2.end();
            ++it) {
            scores.push_back((double)(it->first / XCORR_SCALING));
          }
          sort(scores.begin(), scores.end(), greater<double>());  //sort in decreasing order
          int quantile_pos = (int)(quantile_th*(double)scores.size()+0.5);

          if (quantile_pos < 3)
            quantile_pos = 3;
          quantile_score = scores[quantile_pos]+OFFSET; // Make sure scores positive
        }  //End of Tailor


```
To this code (there are only two new lines):

```
       //Implementation of the Tailor score calibration method, by AKF
        double quantile_score = 1.0;
        if (Params::GetBool("use-tailor-calibration")){
          vector<double> scores;
          double quantile_th = TAILOR_QUANTILE_TH;
          // Collect the scores for the score tail distribution
          for (TideMatchSet::Arr2::iterator it = match_arr2.begin();
            it != match_arr2.end();
            ++it) {
            scores.push_back((double)(it->first / XCORR_SCALING));
          }
          sort(scores.begin(), scores.end(), greater<double>());  //sort in decreasing order
          int quantile_pos = (int)(quantile_th*(double)scores.size()+0.5);

          if (quantile_pos < 3)
            quantile_pos = 3;
          **if (quantile_pos >= scores.size())
            quantile_pos = scores.size()-1;**

          quantile_score = scores[quantile_pos]+OFFSET; // Make sure scores positive
        }  //End of Tailor

```

Could you please test this on your laptop and on the cluster, so that we can be sure that you get the same results? Let me know how this works.

**Comment by younglululu** [comment]
I confirmed that the bug has been fixed after adding the two new lines suggested by Attila
