### ISSUE TITLE
No need to bundle pwiz_bindings_cli.dll and pwiz_data_cli.dll

### ISSUE THREAD

**Issue by chambm** [crux-toolkit/crux-toolkit#532]
Those are for .NET applications that want to access the pwiz libraries (like Skyline, SeeMS, and MSConvertGUI).

**Comment by CharlesEGrant** [comment]
I fixed this by deleting the directories containing this feature from the PWiz source code during the 'configure' step of the pwiz build. I also had to make some changes to the libraries named in our build as linking from pwiz and boost since PWiz actually changed they way they support Thermo RAW files some time ago.
