### ISSUE TITLE
spectrumNativeID

### ISSUE THREAD

**Issue by jvolkening** [crux-toolkit/crux-toolkit#558]
Hello,

Would it be possible to include the `spectrumNativeID` attribute in the percolator pepXML output `<spectrum_query>` elements? It exists in the crux comet output pepXML, and it is needed by some downstream processing tools to match IDs back to the mzML spectra.

If this is a complicated/time-consuming request, it is not critical -- I can write a script to copy the attributes from one file to the other post-run.

Many thanks.

**Comment by wsnoble** [comment]
We are transitioning to having Percolator manage all of its own output files, rather than post-processing the Percolator results to be more similar to other Crux outputs.  As a result of this change, it would be necessary to have this change happen on the Percolator side of things (i.e., by submitting a request via their [issue tracker](https://github.com/percolator/percolator/issues). The challenge I anticipate is figuring out how to get the spectrumNativeID into the Percolator input file.
