### ISSUE TITLE
param-medic Th -> Da or ppm

### ISSUE THREAD

**Issue by ypriverol** [crux-toolkit/crux-toolkit#616]
Hi: 
We are using extensively param-medic to annotate some of the parameters files from PRIDE database. For precursor and fragment tolerances we always use Da or ppm notation, However I see that in a lot of cases for fragment tolerance param-medic returns Th. Can you let me know how I can easily estimate or translate from Th to Da or ppms? 

Regards 
Yasset

**Comment by wsnoble** [comment]
"Th" is Thompson, which is an outmoded scientific unit: https://en.wikipedia.org/wiki/Thomson_(unit)
It's basically Da/charge.

Computing in units of ppm is done like this: (experimental_mass - observed_mass) / experimental_mass * 1e6

Note that you can also use m/z rather than mass, because the charges cancel in the numerator and denominator.
