### ISSUE TITLE
Make three separate sequence columns in Tide

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#622]
Tide should report three separate columns for the peptide sequence: one for the sequence with no modifications, one for the sequence with modifications, and one just for modifications.  The syntax for the latter two column types should mimic that of Comet.

**Comment by bmx8177** [comment]
Why is this necessary? Is the goal to match Comet?

**Comment by wsnoble** [comment]
I think it is convenient to have the unmodified and modified sequence, for different use cases.  And the entry that just contains the mods is much more parseable.

**Comment by mriffle** [comment]
I'll just randomly butt in here (without knowing for sure what's in the current output) and add that if the modifications column included unrounded mod masses (as opposed to those typically found in peptide sequences), that'd be extra useful.

**Comment by wsnoble** [comment]
I believe this is fixed now, Mike -- we report 4 digits by default.  See the [release notes](http://crux.ms/release-notes.html) for Dec 16, 2022.

**Comment by jke000** [comment]
For Comet's text output (examples of which are [found on the output_txtfile parameter page](https://uwpr.github.io/Comet/parameters/parameters_202201/output_txtfile.html)), it reports the three columns that Bill is referring to as follows:

1. "plain_peptide" e.g. TPTTPLPQTPTR
2. "modified_peptide" e.g. K.TPTTPLPQT[79.9663]PTR.R
3. "modifications" e.g. 9_P_79.966331

The "modifications" encoding that specifies position, type, and massdiff, separated by underscores as shown above.  An optional fourth entry could be present to denote if the modification is due to an N- or C-term peptide or protein modification.  Modification "types" encoding are currently "V" for variable mod, "S" for static mod, "P" for PEFF modification, and "p" for PEFF substitution.

**Comment by wsnoble** [comment]
Currently, Tide has "sequence" and "modifications," but no unmodified sequence column. However, the "original target sequence" column has no modifications in it. We should verify that this is still the case in the new tide-index.  If so, then maybe we can just forget this issue (although we should document the lack of mods in the "original target sequence" column somewhere).

**Comment by bmx8177** [comment]
I just checked and in the new tide-index the "original target sequence" column does not contain any modifications. So in principle, we can use this column to get the unmodified sequence of a target sequence. It doesn't work with a decoy sequence though.

Note that this it relevant for tide-search outputs only.

**Comment by wsnoble** [comment]
Fine, I think the upshot is that we can close this issue. I will try to remember to mention this in the updated documentation when I address issue [issue 626](https://github.com/crux-toolkit/crux-toolkit/issues/628).

**Comment by kfattila** [comment]
Once, I get a chance to work on tide, I can easily add the plain sequence to the output. It would need no extra time. Let me know if you still need thiss, and reopen this issue.
