### ISSUE TITLE
Error on unknown CV term from psi-ms (Thermorawfileparser)

### ISSUE THREAD

**Issue by cbielow** [crux-toolkit/crux-toolkit#684]
When using the latest `bioconda::crux-toolkit` (v4.1) from Conda I get the same error on Linux.

related to #615

However, using CRUX from https://noble.gs.washington.edu/crux-downloads/crux-4.2/crux-4.2.Linux.x86_64.zip is fine.

Putting this up here for documentation and maybe someone can push 4.2 to Conda?

**Comment by wsnoble** [comment]
The issue is that we did not create this version of Crux in Conda.  The conda community seems to be very proactive about building packages for software they aren't the maintainers of.  This can be a bit of a problem, because folks may build and submit packages to condo-build that don't fully work. It looks like condo-build has their own package building language like Google Actions or RPM or MacPorts. The solution is to create an official Crux conda package, but this will require investing the 3-4 days to learn the language and the process.

**Comment by cbielow** [comment]
> The issue is that we did not create this version of Crux in Conda. 

Interesting :)

An update to the latest version would be highly appreciated though.
Thanks!

**Comment by acquayefrank** [comment]
Hello @cbielow  this is the official crux-toolkit conda package:

https://anaconda.org/crux-toolkit/crux-toolkit

It should receive regular updates with each release.
