### ISSUE TITLE
building error "openssl/conf.h not found"

### ISSUE THREAD

**Issue by codeworse** [crux-toolkit/crux-toolkit#692]
I have troubles with building crux-toolkit
![photo_2024-09-11 21 40 37](https://github.com/user-attachments/assets/560f515f-edcc-455e-8126-a01a28e70419)
Somehow compiler go into APPLE macros here https://github.com/crux-toolkit/crux-toolkit/blob/master/src/util/crux-utils.cpp#L38 even I compile not in MacOS

**Comment by CharlesEGrant** [comment]
The macro in question is

#ifdef _MSC_VER
#include <boost/wintls.hpp>
#else
**#ifndef __APPLE__**
#include <boost/asio.hpp>
#include <boost/asio/ssl.hpp>
#endif

Note that this is an #ifndef block not an #ifdef block, that is, it's only entered if __APPLE__ is NOT defined, so this is the correct behavior on a non-MacOS platform. 

It looks like the issue may be that the openssl libraries are not installed on your system. This is pretty uncommon. Are you using an older Linux distribution? Can  you try running

openssl version

If openssl is not installed on your system, you will need to install it in order to build crux. You can run the prebuilt binary is openssl is not installed.

**Comment by codeworse** [comment]
OpenSSL 3.0.2 version and I'm building on Ubuntu 22.04. It's even more strange, cause a few days ago I've built the crux just fine.
_P.S. yes with #ifndef my mistake didn't notice_

**Comment by CharlesEGrant** [comment]
Does the directory /usr/include/ssl exist?

**Comment by codeworse** [comment]
Well, no...guess this is the problem, thanks!

**Comment by CharlesEGrant** [comment]
You probably need to install the ssl development package.  Using the dnf package manager this command would be

sudo dnf install openssl-devel

Other package managers will have different names for this. On Ubuntu it's

sudo apt-get install libssl-dev
